### ISSUE TITLE
Weird behavior under missingness in JHU cases

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast-indicators#1469]
The JHU cases signal has some weird behavior in TN around Jan 11.

![Screen Shot 2022-01-18 at 10 00 35 AM](https://user-images.githubusercontent.com/732541/149962200-5283382f-a81f-4480-b387-45b9fb3238fb.png)

The dashboard shows that we report 0 cases per 100k as a 7-day average value on that day, and I have to assume its a missingness bug (the previous 7 days appear to be all missing).

Even the behavior of a 7-day average signal in the days before that we need to carefully inspect to make sure it’s correct.

**Comment by dshemetov** [comment]
I was able to manually rebuild the signal from the raw data at JHU, so I don't think the issue is in our pipeline. The existing data for TN shows a stretch of 7 zeros leading up to and including Jan 11th, so the I think the smoothing is correct. My guess is that it's an issue on the data source side.

![image](https://user-images.githubusercontent.com/1810426/150017320-393df8b6-554c-43b0-b11f-a9807435c8fe.png)

**Comment by dshemetov** [comment]
[Related](https://github.com/CSSEGISandData/COVID-19/issues/5155):
> On January 5, the US state of Tennessee moved to once weekly reporting. The data will be published on Wednesdays and will include the data from the previous Sunday to Saturday period.

**Comment by krivard** [comment]
Wednesdays is smart; if they'd picked Mondays that would've created a nightmare

**Comment by ryantibs** [comment]
Ah ok, thanks.  I thought the 0s were actually NAs, so I didn't understand why it could be behaving as it was.  But given that they're being reported as 0s, then I agree it seems like our smoother is behaving properly.

**Comment by krivard** [comment]
Added to Anomalies.
