### ISSUE TITLE
Take this repo public

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#284]
Before our Fellows start, we must make this repo public. Checklist:

- [x] Verify there is no confidential information here (credentials, restricted data, partner names...)
- [x] Apply the [MIT license](https://opensource.org/licenses/mit-license.php) via LICENSE file and note in README
- [x] Tidy up README and repo metadata to include appropriate links so members of the public who stumble on this will know what it is
- [x] Press the big red button
- [x] Update public docs to point here so people see how indicators work

**Comment by krivard** [comment]
it turns out filter-branch does not _edit_ the commits but rather _replaces_ them with a new version, which should have been obvious in hindsight. There are two ways to propagate the resulting forced changes to all the clones:

* `reset --hard` for each branch in remote
* `rebase`

The first is no good because it will trash all changes that haven't been pushed up to the server.

The second is no good because it will attempt to replay the original versions of each replaced commit, and each of those will generate a conflict that has to be resolved manually. There have been hundreds of such commits, and I'm not going to make everyone do that.

There might be a way to have folks generate patches, but that would require more coordination than we're prepared to do today.

I've removed the disclosure from the contribution guide that's been merged to main, and we'll just cope with it remaining in the history.

@capnrefsmmat we're ready to link to this repo from the public docs.

**Comment by capnrefsmmat** [comment]
See https://github.com/cmu-delphi/delphi-epidata/pull/229
