### ISSUE TITLE
GeoMapper produces invalid counties >80000 for JHU

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#318]
Specifically, `88888` and `99999`. COVIDcast fails any county file with a geo over 80000, so that's not allowed.

This might be related to the 800XX and 900XX codes referenced [here](https://github.com/cmu-delphi/covidcast-indicators/issues/179#issuecomment-689137773) and [here](https://github.com/cmu-delphi/covidcast-indicators/issues/254#issuecomment-683290965); JHU plays pretty fast and loose with their geo coding. It's totally fine for GeoMapper to use 8xxxx and 9xxxx codes internally for geo aggregation, we just can't let them escape into CSV files destined for COVIDcast ingestion.

@dshemetov would you introduce @sgsmob  to the relevant code and documentation here and on JHU's github?

**Comment by dshemetov** [comment]
Ah these are likely coming from the Puerto Rico 72888 and 72999 UIDs, will take a look.

**Comment by dshemetov** [comment]
I've been meaning to make a unified map of all the hand modifications we use in JHU, it might be time.

**Comment by sgsmob** [comment]
So do we need to enforce this in GeoMapper or do we need to have some/all indicators check this later?

**Comment by dshemetov** [comment]
@sgsmob Since this a global requirement for all indicators, I think we should enforce it once in GeoMapper.

**Comment by dshemetov** [comment]
Ah I see, these are not Puerto Rico, but are the Princess Cruises ships. @sgsmob this is the [JHU UID lookup file](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv) from [this repo](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data).
```
84088888,US,USA,840,88888,,Diamond Princess,US,,,"Diamond Princess, US",
84099999,US,USA,840,99999,,Grand Princess,US,,,"Grand Princess, US",
```
We just need to make sure they are dropped from the JHU UID -> FIPS mapping file. Should be a few lines.

**Comment by dshemetov** [comment]
Also the high-level GeoMapper docs are [here](https://github.com/cmu-delphi/covidcast-indicators/tree/main/_delphi_utils_python/data_proc/geomap). The section on geo codes provides general info on the codes we support and the section on source files describes the authorities we get the lookup tables from.

**Comment by dshemetov** [comment]
Reproducing my table of JHU UID -> FIPS mappings:

|Name|JHU UID|Delphi FIPS|Notes|
|----|-------|----|---|
|Dukes&Nantucket|84070002|25007|Weighted Split|
|Dukes&Nantucket|84070002|25019|Weighted Split|
|Dukes|84025007|25007|JHU unused but kept in case of future changes|
|Nantucket|84025019|25019|JHU unused but kept in case of future changes|
|Kansas City|84070003|29095|Weighted Split|
|Kansas City|84070003|29165|Weighted Split|
|Kansas City|84070003|29037|Weighted Split|
|Kansas City|84070003|29047|Weighted Split|
|Alaska|84002158|02270|Recoding Due To FIPS Table Differences|
|Ogalala|84046102|46113|Recoding Due To FIPS Table Differences|
|States (Unused)|840000XX|XX000|State FIPS Code|
|Unassigned|840800XX|XX000|Probable Cases/Deaths for the State Level|
|Out of State|840900XX|XX000|Miscellaneous Cases/Deaths for the State Level|
|Puerto Rico Unassigned|63072888|72000|Probable Cases/Deaths for the State Level|
|Puerto Rico Out of State|63072999|72000|Miscellaneous Cases/Deaths for the State Level|

**Comment by sgsmob** [comment]
This is fixed, no?
