### ISSUE TITLE
Post additional behavior signals from the symptom survey

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#324]
We can define the following signals from the symptom survey data:

* `travel_outside_state_5d`: Percent answering yes to item C6, "In the past 5 days, have you traveled outside of your state?"
* `work_outside_home_5d`: Percent answering yes to item C3, "In the past 5 days, have you gone to work outside of your home?" (Removed in wave 4. Historical data need only be calculated once.)

Additionally, item C13 gives six activities and asks if the respondent has one them in the past 24 hours:

* Gone to work or school outside the place where you are currently staying 
* Gone to a market, grocery store, or pharmacy
* Gone to a bar, restaurant, or cafe 
* Spent time with someone who isn't currently staying with you 
* Attended an event with more than 10 people
* Used public transit

We should report seven-day averages of these, if possible. This will require extra code, since the question is coded as a single column in the CSV with comma-separated selections within the field. We'll have to write something that splits them up and then checks if each selection is present.

Continuation of #18.

**Comment by capnrefsmmat** [comment]
The basic approach is just

```r
data$C13_options <- strsplit(data$C13, ",", fixed = TRUE)
```

for the multi-select options, and this utility function:

```r
#' Test if a specific selection is selected
#'
#' @param vec A list whose entries are character vectors, such as c("14", "15").
#' @param selection one string, such as "14"
#' @return a logical vector; for each list entry, whether selection is contained
#'   in the character vector.
is_selected <- function(vec, selection) {
  selections <- sapply(vec, function(resp) { selection %in% resp })

  return(ifelse(is.na(vec), NA, selections))
}
```

Then we can produce aggregates of the C13 options.

**Comment by capnrefsmmat** [comment]
I propose the following activity signal names:

* `shop_1d`: Percentage of respondents who reported going to a "market, grocery store, or pharmacy" in the past 24 hours
* `restaurant_1d`: "bar, restaurant, or cafe" in past 24 hours
* `spent_time_1d`: "Spent time with someone who isn't currently staying with you" in past 24 hours
* `large_event_1d`: "Attended an event with more than 10 people" in past 24 hours
* `public_transit_1d`: "Used public transit" in past 24 hours
* `work_outside_home_1d`: Went to "work or school outside the place where you are currently staying" in past 24 hours

I have code ready to generate these, so we can release them soon. @RoniRos Any name changes you'd like to request before we prepare these for publication?

**Comment by RoniRos** [comment]
These look fine to me.  Perhaps the only change I might suggest is to something like "event_gt10_people", since it is more specific than "large", and we may have future signals (from survey or otherwise) that use a different threshold.

Btw, there is no need to consult me on survey signal names, unless you actively want my advice or feedback, e.g. in the case of epi-related terms.  Also, by now there are plenty of existing signal names to guide our choices.

On a related note: In the API doc and elsewhere, we refer to the survey as a "symptoms survey", but it has long ago morphed into something much more general.  So "symptoms survey" is perhaps no longer appropriate.  Should we change the references to "public health survey" or "public survey" (i.e. survey of the general public), or "pandemic survey" or some other name?   The ideal name would depend on how you envision the survey evolving.
