### ISSUE TITLE
Cumulative case and death rates dropped on Oct 27 

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast-indicators#467]
Cumulative case and death rates, coming from the indicator-combo signal, dropped on Oct 27.  See the screenshots below from the COVIDcast map.  

The counts themselves do not appear to drop, see the following two screenshots.

Lastly, both case and death rates and counts are missing on Nov 2: I'm not sure it this is related to the JHU struggles we've been having.  I couldn't find an issue on this so I'm pointing it out here.  

cc @krivard, and @jingjtang who I think worked on the cases and deaths signals

![Screen Shot 2020-11-09 at 11 47 20 AM](https://user-images.githubusercontent.com/732541/98571264-5e698a80-2282-11eb-868c-3168a1b11222.png)

![Screen Shot 2020-11-09 at 11 46 49 AM](https://user-images.githubusercontent.com/732541/98571253-5a3d6d00-2282-11eb-9ea8-61bebdda42e3.png)

![Screen Shot 2020-11-09 at 11 47 28 AM](https://user-images.githubusercontent.com/732541/98571314-6aede300-2282-11eb-9ece-2034d3ef0923.png)

![Screen Shot 2020-11-09 at 11 46 59 AM](https://user-images.githubusercontent.com/732541/98571321-6d503d00-2282-11eb-9226-871686e2280c.png)

**Comment by ryantibs** [comment]
@krivard @jingjtang Just an update that this appears to be fixed now, on the COVIDcast map.  

There's no longer a drop in cumulative case rates or cumulative death rates, and there's also no longer data that appears to be missing.  

So I guess we can close this issue?  @krivard I'll let you do that.  That said, it would be probably good to understand why this happened, to see if we still need to fix something to prevent it popping up again.  

(Also, I didn't intend to assign @nmdefries that must have been a mistake, my bad.)

**Comment by krivard** [comment]
This work  is under way -- the combo cases/deaths indicator was running in a mode where it just updated the last week of data, instead of generating the full time span and using the archive/diff utility to extract just the updated rows. For the last few days it's been generating dense issues, which is not sustainable but did fix the symptom identified in this issue. Tonight's run will be the first using the uniform issue definition, and if that works, I'll close this then.

(Also: Nat is auto-assigned to data quality issues, since he's currently the data validation tsar)
