### ISSUE TITLE
Move population-based prop computation into the utility so it can be adequately tested

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#537]
Both USAFacts and JHU aggregate prop signals by population from county to state, a process which is susceptible to error. Specifically, the population of the megafips is equal to the state population, and megafips + all individual counties yields state population + population of each individual county = 2x the state population.

Testing this effect in individual indicators will always result in us playing catch-up when new counts-based indicators are added which include population-based prop signals aggregated from the county level upwards.

We should instead pursue a refactor which moves population-prop aggregation into the utility, so that it can be tested once there, and used everywhere in confidence.

**Comment by chinandrew** [comment]
> Specifically, the population of the megafips is equal to the state population

Why is this the case? Does zeroing it out cause a div/0 error elsewhere?

**Comment by krivard** [comment]
> Does zeroing it out cause a div/0 error elsewhere?

Yes -- prop signals divide by the population; the best thing a megafips prop signal can divide by is the state population

**Comment by chinandrew** [comment]
Per a conversation with @krivard  and @dshemetov, we're going with an approach where replace_geocode will do the "zero out the megafips populations so we don't double count" logic  that are [currently implemented in JHU](https://github.com/cmu-delphi/covidcast-indicators/blob/961356f8f7c6d2f3d919c9967f448e7f8e08b4c7/jhu/delphi_jhu/geo.py#L40-L44) and USAfacts. This requires the population column to be added (it will throw a warning otherwise) before the geomapping. After mapping, the indicators will be able to do a direct prop=value/population computation.

We also discussed supporting more geographies in add_population_column and having that operation done after geomapping, but didn't end up doing that because we want the denominator to be the population of all the reported geographies and not the population of the full region (e.g. if 5 counties are reported in a state, use the population from all 5 counties, not the state population).
