### ISSUE TITLE
Release CHNG-DV

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#591]
- [Link to PR](https://github.com/cmu-delphi/covidcast-indicators/pull/587)
- Proposed release version: hotfix

This signal mirrors the definition of HSP's `doctor-visits`, and is suitable for direct replacement of `doctor-visits` in the map.

- [x] API [documentation](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast-signals/chng.md)
- [x] API mailing list notification

- [x] Statistical review (usually [correlations](https://github.com/cmu-delphi/covidcast/tree/main/docs/R-notebooks))
- [x] Signal name review (usually [Roni](https://docs.google.com/document/d/10hGd4Evce4lJ4VkWaQEKFQxvmw2P4xyYGtIAWF52Sf8/edit?usp=sharing))
- [x] Verify licensing terms and any applicable DUA restrictions

- [x] Visual review
- [x] [Signal description pop-up text](https://docs.google.com/document/d/1Yi_ueKvASwyzm6ZJEcrStk5qVIKz94N2yEHlklfnEig/edit#bookmark=id.3k0igtdpsx2o) draft and review

**Comment by rumackaaron** [comment]
@Akvannortwick Here is a draft of the announcement, modified from earlier announcements.

Today I am pleased to announce an additional indicator publicly available in the COVIDcast API: percentage of outpatient doctor visits that involve COVID-like illness (CLI) from Change Healthcare.

This indicator is analogous to the "Doctor Visits" indicator, but the new indicator comes from Change Healthcare's data instead of other health service partners. Our new indicator is calculated from data that covers approximately 45% of U.S. patients. We are excited about this indicator because it is based on much more data than the original "Doctor Visits" indicator.

The %CLI indicator complements our other indicator based on Change Healthcare's data, the %COVID indicator. The %COVID indicator tracks confirmed COVID-19, whereas the %CLI indicator tracks COVID-like illness, which is a broader condition defined by a set of symptoms (a syndrome) that could be due to COVID-19 but could also be due to other pathogens such as influenza, RSV, and others.

Details are available here: https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/chng.html

**Comment by krivard** [comment]
This has been released in the API; remains is to switch over the map DV signal to CHNG-DV. @tildechris what's needed for that? I have the signal popup text ready in [the staging doc](https://docs.google.com/document/d/1Yi_ueKvASwyzm6ZJEcrStk5qVIKz94N2yEHlklfnEig/edit?usp=sharing); it's meant as a drop-in replacement for the existing "COVID-Related Doctor Visits" entry.

**Comment by tildechris** [comment]
You should be able to just finalize your copy changes.  For book-keeping, I'd add name that revision to make it explicit what changed, but that doesn't affect pulling the metadata into www-covidcast.

It *should* just make it into the next staging build, but I see that we have some builds since your edits and I'm not seeing any data.  It looks ok in the [dev](https://dev--cmu-delphi-covidcast.netlify.app/?date=20201205&region=42003) which the exception of the signal not being in the URL. I'll check if that's on purpose.

**Comment by krivard** [comment]
Cool, I'll transfer it over to the production doc.

**Comment by krivard** [comment]
Transferred and finalized with Roni's OK.

**Comment by krivard** [comment]
Deployed! 🎉
