### ISSUE TITLE
National/HHS signal should not be calculated if too few states are available.

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/covidcast-indicators#946]
**Actual Behavior:**

As of right now (March 21 ~noon), in "Explore an Indicator", Case data is available for all states thru March 18, except for Puerto Rico it is also available for March 19.  It appears that for March 19 the National Case numbers are calculated from the PR value only, which results in an apparent sharp dip in the national signal (from ~15 to ~5).

**Expected behavior**

I suggest that, for any signal, a national/HHS signal(s) not be calculated unless at least X of the constituent states are available.  Maybe X=75%?  50%?

Are there any signals where this is a problem also at the state-county level?

**Comment by krivard** [comment]
This is a combo cases problem and *only* a combo cases problem, since that's the only indicator we have that re-aggregates information from multiple upstream sources with potentially differing lags. I've documented this more specifically in #947 for tracking the fix.

I don't think we want to try and pick a threshold for conditionally reporting some geo levels, since there will be more special cases than general cases: doctor-visits, hospital-admissions, bar visits, quidel tests all have genuinely low coverage for at least some reference dates, but hhs and nation figures are still useful there.
